message/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import Index, Conf, delete

app_name = 'message'

urlpatterns = [
    path('', Index, name= 'Index'),
    path('<int:pk>/', delete, name="delete"),
    path('confirmation/', Conf, name= 'confirmation'),
]

story7/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("message.urls")),
]

message/models.py
from django.db import models

# Create your models here.
class Message(models.Model):
    name = models.CharField(max_length= 30)
    message = models.CharField(max_length =200)
    time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name}"

message/forms.py
from django import forms

class MessageForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Name',
        'type' : 'text',
    }))
    message = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'message',
        'type' : 'text',
    }))

message/views.py
from django.shortcuts import render, redirect
from .models import Message
from .forms import MessageForm

def Index(request):
    if request.method=="POST":
        frm = MessageForm(request.POST)
        if frm.is_valid():
            frm2 = Message()
            frm2.name = frm.cleaned_data["name"]
            frm2.message= frm.cleaned_data["message"]
            frm2.save()
        return redirect("/confirmation")
    frm = MessageForm()
    frm2 = Message.objects.all()
    frm_dictio = {
        'frm':frm, #form
        'frm2':frm2 #model/isi formnya
    }
    return render(request,'story7.html',frm_dictio)

def Conf(request):
    msg_input = Message.objects.last()
    conf_dictio = {
        'msg_input': msg_input}
    return render(request, 'conf.html',conf_dictio)

def delete(request, pk):
    if request.method == "POST":
        frm = MessageForm(request.POST)
        if frm.is_valid():
            frm2 = Message()
            frm2.name = frm.cleaned_data["name"]
            frm2.message = frm.cleaned_data["message"]
            frm2.save()
        return redirect("/confirmation")
    else:
        Message.objects.filter(pk = pk).delete()
        frm = MessageForm()
        frm2 = Message.objects.all()
        msg_dictio ={
            'frm' : frm,
            'frm2': frm2
        }
        return render(request, 'story7.html', msg_dictio)

message/templates/conf.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Are You Sure?</title>
    <link rel = "stylesheet" type = "text/css" href = "{% static 'conf.css' %}">

</head>
<body>
<div class ="adj">
    <p class="r">Are You Sure?</p>
    <div class="teks">
        <ul style="list-style: none;">
            <li>{{msg_input.name}}</li>
            <li style="font-size: 20px;">"{{msg_input.message}}"</li>
        </ul>
    </div>
    <button ><a class="btn btn-primary btn-lg" href="{% url 'message:delete' pk=msg_input.pk %}" type="submit" role="button">No</a></button>
    <button ><a class="btn light btn-lg" href="{% url 'message:Index' %}" type="submit" role="button">Yes</a></button>
</div>
</body>
</html>

message/templates/story7.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Hello!</title>
    <link rel = "stylesheet" type = "text/css" href = "{% static 'story7.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">

</head>

<body>
<iframe src="http://free.timeanddate.com/clock/i78fikmf/n108/tlid38/fn12/fcfff/tct/pct" frameborder="0" width="70" height="18" allowTransparency="true"></iframe>

<p style="color: #3b8d99">&copy;2020 Nikita Jacey</p>
    <p class="line anim-typewriter">What's on your mind?</p>

    <div class="form">
        <form action='' method="POST">
            {% csrf_token %}
            <ul style="list-style: none;">
                <li>Name  <br>{{frm.name}}</li>
                <br>
                <li>Message <br> {{frm.message}}</li>
                <br>
                <button name="submit" type="submit" class="buttons">Submit</button>

            </ul>
        </form>
    </div>
<div id = tulisan>
    <h3>Messanges</h3>
    <div class="table">
        <table class="table1">
            {% for i in frm2%}
            <ul style="border-style: solid; border-color: white;list-style: none;border-width: thin;padding: 1em;">
                <li>{{i.name}}</li>
                <li>"{{i.message}}"</li>
                <li style="font-size: 10px;">{{i.time}}</li>
            </ul>
            {% endfor %}
        </table>
    </div>
</div>
</body>

</body>
</html>